services:
  # Synapse (Matrix server)
  synapse:
    image: docker.arvancloud.ir/matrixdotorg/synapse:v1.121.1
    container_name: synapse
    restart: always
    volumes:
      - ./data/synapse:/data
      - /etc/localtime:/etc/localtime:ro
      - ./data/bridges/whatsapp/registration.yaml:/opt/appsvc/bridges/whatsapp.registration.yaml:ro
    environment:
      - SYNAPSE_SERVER_NAME=matrix-srv.xaas.ir
      - SYNAPSE_REPORT_STATS=yes
    ports:
      - "8008:8008"
      - "8448:8448"
      - "9001:9000" #[prometheus]
    #command: ["generate"]
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - synapse_network
  ## whatsapp
  mautrix-whatsapp:
    container_name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:latest
    privileged: true # /shrug
    #user: 991:991
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
    - ./data/bridges/whatsapp:/data
    networks:
      - synapse_network

  ## redis
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 3s
      timeout: 3s
    networks:
      - synapse_network
  # Postgres database
  postgres:
    image: docker.arvancloud.ir/postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: mewomewo123
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      LANG: C
      LC_ALL: C
    shm_size: 1g
    runtime: runc
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - postgres_password
    networks:
      - synapse_network

  # Element Web (Matrix web client)
  element-web:
    image: docker.arvancloud.ir/vectorim/element-web:v1.11.89
    container_name: element-web
    restart: always
    volumes:
      - ./data/element:/app/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    networks:
      - synapse_network

  # Nginx (Reverse Proxy)
  nginx:
    image: docker.arvancloud.ir/nginx:1.27.3
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
      - ./nginx/etc/ssl:/etc/nginx/ssl:ro
      - ./nginx/var/log/nginx:/var/log/nginx
      - ./nginx/var/nginx/cache:/var/nginx/cache
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "443:443"
    depends_on:
      - synapse
      - element-web
    networks:
      - synapse_network

networks:
  synapse_network:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password